kind: Service
apiVersion: v1
metadata:
  name: jogo
  namespace: outrojogo
spec:
  selector:
    app: jogo
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
